### ISSUE TITLE
Checksum Summary Files

### ISSUE THREAD

**Issue by edziegle** [gradle/gradle-checksum#2]
First of all, thank you so much for this plugin, it is already saving me a lot of effort.  I was hoping though that the plugin could be extended to produce a checksum summary file similar to how the `checksum-maven-plugin` does ([see here](https://checksum-maven-plugin.nicoulaj.net/examples/generating-checksum-summary-files.html)).

To give some background on my use case, I am on a project that has these checksum summary files/reports as a part of our process; checksums for `.java`, `.class` and `.js` are included in the report.  In the past we've used the `checksum-maven-plugin` to accomplish this step, but we'd like to move away from maven and have a holistic Gradle build, without having to reimplement this process in our code. Having this as a part of Gradle is good for controllability/predictability of the process.

I am happy to help contribute to this solution if it is a feasible enhancement to the plugin. I wanted to get feedback before I started on anything.

**Comment by oehme** [comment]
Afaik this plugin is not under active development. @eljobe Why was it published under org.gradle (which implies we'll maintain it)? Is there anyone else at Gradle who knows what the intended direction of this plugin is?

@edziegle I'd like to figure out the right home and owner for this plugin before we go deeper into this issue.

**Comment by big-guy** [comment]
@oehme It was created for generating checksums for the Gradle distribution before we publish it to services.gradle.org.  So I think there's no intention of ever including this into the Gradle distribution as a built-in plugin or developing it beyond what we needed.

If this is a good starting point for something @edziegle needs, forking it is probably the easiest thing to do.

**Comment by edziegle** [comment]
Thanks for the feedback folks, the context around how you use this plugin is helpful. If the plugin is not intended to compete/be feature parity with the maven plugin, then I agree it will probably be best for me to fork the plugin and move forward from there.
