### ISSUE TITLE
Missing method with Gradle 5.0

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle-checksum#5]
Trying to run this in a Gradle 5.0 project doesn't work. I get a NoSuchMethodError when it trys to load `com.google.common.hash.Hashing.sha384()Lcom/google/common/hash/HashFunction`.

Build scan can be found https://scans.gradle.com/s/6o3tpx6uvkcvw/failure?openFailures=WzBd&openStackTraces=WzNd#top=0

**Comment by jprinet** [comment]
I'm kind of digging up this one, but could you please upgrade to a more recent version @ThadHouse ?
