### ISSUE TITLE
Plugin should not delete all files that have a checksum extension

### ISSUE THREAD

**Issue by jadbaz** [gradle/gradle-checksum#6]
So this is my use case. I'm using the [distribution plugin](https://docs.gradle.org/current/userguide/distribution_plugin.html) and outputting a tar file and a zip file in the standard "distributions" directory.

Then I have 2 tasks to generate a checksum for these 2 distributions. The problem here is that one deletes the other
This is happening at [Checksum.java#L98](https://github.com/gradle/gradle-checksum/blob/master/src/main/java/org/gradle/crypto/checksum/Checksum.java#L98)

Is this the intended behavior? Should we be deleting all files that have any checksum extension? Should we not instead delete all files named <fileName>.<algorithm>?

**Comment by marcphilipp** [comment]
@jadbaz Can you use a single task instead?

**Comment by jadbaz** [comment]
Can you post an example of that?

**Comment by jadbaz** [comment]
OK, this did the trick
```
task createDistributionChecksums(type: Checksum, dependsOn: distZip) {
    files = files(distZip.outputs.files, distTar.outputs.files)
    outputDir = new File(project.buildDir, "distributions")
    algorithm = Checksum.Algorithm.MD5
}
```

But I still think this is a bug

**Comment by johnmgoodman** [comment]
I'm experiencing this issue as well. I need to generate several checksums so I'm trying to configure some checksum tasks in a loop iterating over a few of the algorithms:

```groovy
[
  Checksum.Algorithm.MD5,
  Checksum.Algorithm.SHA256,
  Checksum.Algorithm.SHA512
].each { hashAlgorithm ->
  def checksumTask = tasks.register("create${hashAlgorithm}Checksums", Checksum) {
    group = "Project Distribution"
    files = distTar.outputs.files
    algorithm = hashAlgorithm
    outputDir = project.ext.deliverablesDirectory
  }
  distTar.finalizedBy(checksumTask)
}
```

All of the tasks run, but I only end up with the checksum of the last one that runs.

**Comment by jprinet** [comment]
In such cases, having a separate folder for each checksum algorithm or distribution type should do the trick
